dist: trusty
sudo: required
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_CUDA=OFF
    - os: linux
      compiler: gcc
      env: BUILD_CUDA=ON
    - os: linux
      compiler: clang
      env: BUILD_CUDA=OFF

cache:
  apt: true

install:
  - ./.travis/install.sh

script:
  - ./.travis/build.sh

notifications:
  webhooks: https://code.facebook.com/travis/webhook/
