version: 2.1

# bump

jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            set -e
            apt-get update
            apt-get install -y build-essential cmake ninja
      - run:
          name: Build
          command: |
            set -e
            mkdir build
            cd build
            cmake ../ -GNinja
            ninja
