version: 2.1

jobs:
  build:
    parameters:
      docker_image:
        type: string
        default: ""
    docker:
      - image: << parameters.docker_image >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y build-essential cmake
      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake ../
            make

workflows:
  build:
    jobs:
      - build:
          name: gcc5
          docker_image: ubuntu:16.04
      - build:
          name: cuda9.2
          docker_image: nvidia/cuda:9.2-devel-ubuntu18.04
      - build:
          name: cuda10.1
          docker_image: nvidia/cuda:10.1-devel-ubuntu18.04
