version: 2.1

# bump

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:xenial-scm
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            dpkg -l
            sudo apt-get update
            sudo apt-get install -y build-essential cmake ninja
      - run:
          name: Build
          command: |
            pwd
            env
            mkdir build
            cd build
            cmake ../ -GNinja
            ninja
