version: 2.1

jobs:
  cpu_gcc5:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            set -e
            sudo apt-get update
            sudo apt-get install -y build-essential cmake ninja
      - run:
          name: Build
          command: |
            set -e
            mkdir build
            cd build
            cmake ../ -GNinja
            ninja
